import { Boss } from './types';
export default {
    name: 'nex_melee',
    phases: [
        'Phase 1',
        'Phase 2 - nex (1/2)',
        'Phase 2 - amalg',
        'Phase 2 - nex (2/2)',
        'Phase 3',
        'Pillar - umbra',
        'Pillar - glacies',
        'Pillar - cruor',
        'Pillar - fumus',
        'Phase 4',
    ],
    rotations: [
        [
            'Berserk',
            'Greater_Barge',
            'Backhand',
            'Greater_Flurry',
            'Freedom',
            'Hurricane',
            'Cleave',
            'Decimate',
            'Assault',
            'Backhand',
        ],
        [
            'Storm_Shards',
            'Weapon_Special_attack',
            'Anticipate',
            'Greater_Barge',
            'Greater_Flurry',
            'Backhand',
            'Cleave',
            'Hurricane',
        ],
        [
            'Decimate',
            'Sever',
            'Freedom',
            'Cleave',
        ],
        [
            'Decimate',
            'Greater_Fury',
            'Bladed_Dive',
        ],
        [
            'Berserk',
            'Greater_Barge',
            'Backhand',
            'Cleave',
            'Limitless',
            'Assault',
            'Anticipation',
            'Hurricane',
            'Greater_Flurry',
            'Decimate',
            'Backhand',
            'Cleave',
            'Greater_Fury',
            'Forceful_Backhand',
        ],
        [
            'Sever',
            'Seren_Godbow',
            'Decimate',
            'Freedom',
            'Cleave',
        ],
        [
            'Hurricane',
            'Assault',
            'Cleave',
            'Decimate',
        ],
        [
            'Sever',
            'Greater_Flurry',
            'Cleave',
            'Decimate',
            'Greater_Fury',
        ],
        [
            'Berserk',
            'Backhand',
            'Cleave',
            'Decimate',
            'Sever',
        ],
        [
            'Assault',
            'Cleave',
            'Greater_Fury',
            'Backhand',
            'Hurricane',
        ],
    ],
} as Boss;
